stages:
  - create-infra-stage

create-bucket-job:
  stage: create-infra-stage
  tags:
    - s3
    - static
  before_script:
    # commented out values not valid in my environment, I need to populate these intermittently
    #- aws configure set aws_default_region $AWS_DEFAULT_REGION
    #- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    #- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    #- aws configure set aws_session_token $AWS_SESSION_TOKEN
    - terraform init
    - terraform validate  #check code
  script:
    - terraform plan
    - terraform apply --auto-approve